name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main  # Trigger deployment only on push to main branch

jobs:
  deploy:
    name: Deploy Frontend to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/reptrack-frontend
            git pull origin main
            npm install
            npm run build
            sudo nginx -t && sudo systemctl reload nginx
            echo "✅ Frontend deployment completed!"
            sudo systemctl status nginx --no-pager -l
